zed_node:
  auto_exposure_gain: true
  auto_whitebalance: true
  brightness: 4
  contrast: 4
  depth:
    depth_downsample_factor: 0.5
    depth_registered:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    depth_stabilization: 1
    max_depth: 12
    min_depth: 0.35
    openni_depth_mode: true
    quality: 1
    sensing_mode: 0
  depth_confidence: 100
  depth_texture_conf: 100
  exposure: 100
  gain: 100
  gamma: 8
  general:
    base_frame: base_link
    camera_flip: false
    camera_model: zedm
    camera_name: zedm
    gpu_id: -1
    grab_frame_rate: 15
    resolution: 2
    self_calib: true
    serial_number: 0
    svo_compression: 2
    verbose: false
    zed_id: 0
  hue: 0
  left:
    image_rect_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    image_rect_gray:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  left_raw:
    image_raw_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    image_raw_gray:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  mapping:
    clicked_point_topic: /clicked_point
    fused_pointcloud_freq: 1.0
    mapping_enabled: false
    max_mapping_range: -1
    resolution: 0.05
  object_detection:
    body_fitting: false
    confidence_threshold: 70
    max_range: 15.0
    mc_animal: true
    mc_bag: true
    mc_electronics: true
    mc_fruit_vegetable: true
    mc_people: true
    mc_sport: true
    mc_vehicle: true
    model: 0
    object_tracking_enabled: false
    od_enabled: false
  point_cloud_freq: 10.0
  pos_tracking:
    area_memory: true
    area_memory_db_path: zed_area_memory.area
    fixed_z_value: 0.0
    floor_alignment: false
    imu_fusion: true
    init_odom_with_first_valid_pose: true
    initial_base_pose:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    map_frame: map
    odometry_frame: odom
    path_max_count: -1
    path_pub_rate: 2.0
    pos_tracking_enabled: true
    publish_map_tf: true
    publish_tf: true
    save_area_memory_db_on_exit: false
    two_d_mode: false
  pub_frame_rate: 15.0
  rgb:
    image_rect_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    image_rect_gray:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  rgb_raw:
    image_raw_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    image_raw_gray:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  right:
    image_rect_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    image_rect_gray:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  right_raw:
    image_raw_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
    image_raw_gray:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  saturation: 4
  sensors:
    max_pub_rate: 200.0
    publish_imu_tf: true
    sensors_timestamp_sync: false
  sharpness: 4
  stereo:
    image_rect_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  stereo_raw:
    image_raw_color:
      compressed:
        format: jpeg
        jpeg_optimize: false
        jpeg_progressive: false
        jpeg_quality: 80
        jpeg_restart_interval: 0
        png_level: 9
      compressedDepth:
        depth_max: 10.0
        depth_quantization: 100.0
        format: png
        png_level: 9
      theora:
        keyframe_frequency: 64
        optimize_for: 1
        quality: 31
        target_bitrate: 800000
  stream: ''
  svo_file: ''
  video:
    extrinsic_in_camera_frame: true
    img_downsample_factor: 0.5
  whitebalance_temperature: 0
zedm_description: "<?xml version=\"1.0\" ?>\n<!-- ===================================================================================\
  \ -->\n<!-- |    This document was autogenerated by xacro from /home/roblab20/catkin_ws/src/zed-ros-wrapper/zed_wrapper/urdf/zed_descr.urdf.xacro\
  \ | -->\n<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                \
  \                 | -->\n<!-- ===================================================================================\
  \ -->\n<!--\nCopyright (c) 2020, STEREOLABS.\n\nAll rights reserved.\n\nTHIS SOFTWARE\
  \ IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\"AS IS\" AND ANY EXPRESS\
  \ OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\nLIMITED TO, THE IMPLIED WARRANTIES\
  \ OF MERCHANTABILITY AND FITNESS FOR\nA PARTICULAR PURPOSE ARE DISCLAIMED. IN NO\
  \ EVENT SHALL THE COPYRIGHT\nOWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\
  \ INCIDENTAL,\nSPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n\
  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\nDATA, OR\
  \ PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\nTHEORY OF LIABILITY,\
  \ WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n(INCLUDING NEGLIGENCE OR OTHERWISE)\
  \ ARISING IN ANY WAY OUT OF THE USE\nOF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY\
  \ OF SUCH DAMAGE.\n-->\n<robot name=\"stereolabs_camera\">\n  <material name=\"\
  zed_mat\">\n    <color rgba=\"0.8 0.8 0.8 0.8\"/>\n  </material>\n  <material name=\"\
  zedm_mat\">\n    <color rgba=\"0 0 0 0.9\"/>\n  </material>\n  <material name=\"\
  zed2_mat\">\n    <color rgba=\"0.25 0.25 0.25 0.99\"/>\n  </material>\n  <material\
  \ name=\"zed2i_mat\">\n    <color rgba=\"0.25 0.25 0.25 0.99\"/>\n  </material>\n\
  \  <!-- Camera mounting point (the threaded screw hole in the bottom) -->\n  <link\
  \ name=\"zedm_base_link\"/>\n  <joint name=\"zedm_base_joint\" type=\"fixed\">\n\
  \    <parent link=\"base_link\"/>\n    <child link=\"zedm_base_link\"/>\n    <origin\
  \ rpy=\"0.0 0.0 0.0\" xyz=\"0.0 0.0 0.0\"/>\n  </joint>\n  <!-- Camera Center -->\n\
  \  <link name=\"zedm_camera_center\">\n    <visual>\n      <origin rpy=\"0 0 0\"\
  \ xyz=\"0.0 0 0\"/>\n      <geometry>\n        <mesh filename=\"package://zed_interfaces/meshes/zedm.stl\"\
  />\n      </geometry>\n      <material name=\"zedm_mat\"/>\n    </visual>\n    <collision>\n\
  \      <geometry>\n        <mesh filename=\"package://zed_interfaces/meshes/zedm.stl\"\
  />\n      </geometry>\n    </collision>\n  </link>\n  <joint name=\"zedm_camera_center_joint\"\
  \ type=\"fixed\">\n    <parent link=\"zedm_base_link\"/>\n    <child link=\"zedm_camera_center\"\
  />\n    <origin rpy=\"0 0.0 0\" xyz=\"0 0 0.01325\"/>\n  </joint>\n  <!-- Left Camera\
  \ -->\n  <link name=\"zedm_left_camera_frame\"/>\n  <joint name=\"zedm_left_camera_joint\"\
  \ type=\"fixed\">\n    <parent link=\"zedm_camera_center\"/>\n    <child link=\"\
  zedm_left_camera_frame\"/>\n    <origin rpy=\"0 0 0\" xyz=\"0 0.03 0\"/>\n  </joint>\n\
  \  <link name=\"zedm_left_camera_optical_frame\"/>\n  <joint name=\"zedm_left_camera_optical_joint\"\
  \ type=\"fixed\">\n    <origin rpy=\"-1.5707963267948966 0.0 -1.5707963267948966\"\
  \ xyz=\"0.0 0 0\"/>\n    <parent link=\"zedm_left_camera_frame\"/>\n    <child link=\"\
  zedm_left_camera_optical_frame\"/>\n  </joint>\n  <!-- Right Camera -->\n  <link\
  \ name=\"zedm_right_camera_frame\"/>\n  <joint name=\"zedm_right_camera_joint\"\
  \ type=\"fixed\">\n    <parent link=\"zedm_camera_center\"/>\n    <child link=\"\
  zedm_right_camera_frame\"/>\n    <origin rpy=\"0 0 0\" xyz=\"0 -0.03 0\"/>\n  </joint>\n\
  \  <link name=\"zedm_right_camera_optical_frame\"/>\n  <joint name=\"zedm_right_camera_optical_joint\"\
  \ type=\"fixed\">\n    <origin rpy=\"-1.5707963267948966 0.0 -1.5707963267948966\"\
  \ xyz=\"0.0 0 0\"/>\n    <parent link=\"zedm_right_camera_frame\"/>\n    <child\
  \ link=\"zedm_right_camera_optical_frame\"/>\n  </joint>\n  <link name=\"base_link\"\
  />\n</robot>\n\n"
