
hydra:
  run:
    dir: ${path:}/${recording.bag_folder}/saved_configs/recorder_configs/

topics:
  tf_static: /tf_static
  tf: /tf
  imu: /zedm/zed_node/imu/data
  rgb: /zedm/zed_node/rgb/image_rect_color/compressed
  depth:  /zedm/zed_node/depth/depth_registered/compressed
  pcl: /zedm/zed_node/point_cloud/cloud_registered
  pose: /zedm/zed_node/pose_with_covariance

recording:
  script: record_zed.sh
  prefix: null # optional
  compression: true
  bag_folder: ../../bag/bag_batch_${now:%Y-%m-%d}_${now:%H-%M-%S}
  camera_params_folder: ${recording.bag_folder}/saved_configs/recorder_configs/camera_params
  topics_to_rec: 
    # - tf
    # - tf_static
    - rgb
    - depth
    # - odom
    # - imu


