
hydra:
  run:
    dir: ${path:}/${recording.bag_folder}/saved_configs/recorder_configs/

topics:
  tf: /tf
  imu: /zedm/zed_node/imu/data
  rgb: /zedm/zed_node/rgb/image_rect_color
  depth: /zedm/zed_node/depth/depth_registered
  confidence: /zedm/zed_node/confidence/confidence_map
  disparity: /zedm/zed_node/disparity/disparity_image
  pcl: /zedm/zed_node/point_cloud/cloud_registered

recording:
  script: record_zed.sh
  label: null                   # 1 = GL | 2 = SA | 3 = SD | 9 = W
  set: null
  bag_folder: ../../bag/bag_batch_${now:%Y-%m-%d}_${now:%H-%M-%S}_${recording.set}
  camera_params_folder: ${recording.bag_folder}/saved_configs/recorder_configs/camera_params
  topics_to_rec: 
    #- tf;  sdf
    #- odom
    #- pose
    - imu
    - rgb
    - depth
    #- pcl
    #- confidence
    #- disparity

