
hydra:
  run:
    #dir:  /home/zion/catkin_ws/src/ros_env_prediction/env_recorder_pkg/config/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    dir: /home/roblab20/catkin_ws/src/Exo_Intent/zion_zed_ros_interface/config/saved_configs/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    #dir: ./conf/recorder/records_configs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    #dir: outputs/${now:%Y-%m-%d_%H-%M-%S}/rate:${recorder.rate}


topics:
  tf: /tf
  imu: /zedm/zed_node/imu/data
  rgb: /zedm/zed_node/rgb/image_rect_color
  depth: /zedm/zed_node/depth/depth_registered
  confidence: /zedm/zed_node/confidence/confidence_map
  disparity: /zedm/zed_node/disparity/disparity_image


recording:
  script: record_zed.sh
  save_dir: 
  #script: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/scripts/brings_up/record_zed.sh
  bag_folder: ../../bag
  #bag_folder: /home/nimibot/catkin_ws/src/ros_env_prediction/env_recorder_pkg/bag
  camera_params_folder: ../../config/saved_configs/recorder_configs/${now:%Y-%m-%d}/${now:%H-%M-%S}/camera_params 
  topics_to_rec:
    #- tf
    #- odom
    #- pose
    - imu
    - rgb
    - depth
    #- pcl
    #- confidence
    #- disparity

